### ISSUE TITLE
kvmalloc这个函数是怎么移植的？

### ISSUE THREAD

**Issue by 996refuse** [zhiyihuang/xv6_rpi_port#4]
应该是通过 kvmalloc -> setupkvm_new 来配置内核页表的吧？为什么 main 没有 call kvmalloc?
神奇的是，kernel 代码竟然没有跑飞。

**Comment by zhiyihuang** [comment]
kvmalloc is not needed as the kernel page table is reserved initially in entry.s and will never change.

**Comment by 996refuse** [comment]
注意到了，感谢解答
